asins:
  - B0B68MLDZX
  - B00MINEUEO
  - B00TC5IA2E
  - B07QPCKGL4
  - B089Z96M1T
  - B00S5SAFDQ
  - B00ZFS87LQ
  - B00TC5IHI6
  - B0F4ZFLD75
  - B0C77HQZ17
  - B075L95WPQ
  - B0F43LVQDM
  - B00MHP9DA4
  - B07QPCKGL4
  - B00XCCPOC2
  - B00MHQ8JKS
  - B08X1SX524
  - B00RLK8UXG
marketplace: "IN"
